### ISSUE TITLE
Generated Charts Thoughts

### ISSUE THREAD

**Issue by Michael-J-Ward** [rustype/typestate-rs#3]
I think the auto-gen state charts guaranteed to stay in line with the code is a killer feature.

A few bike-shedding UX improvements I wanted to see what you think

- [x] Allow ChoiceNode edge labels via annotation to the ChoiceEnum variants - either through an annotation `#[label("out of retries")]` or by grabbing the variant's doc comment like the `displaydoc` crate

- [X] Configurable asset destination - instead of populating the `root` directory, allow the user to configure it like by setting an env variable.

Are you accepting outside contributions?

**Comment by jmg-duarte** [comment]
Regarding your suggestions
1. That is a *great* idea but the underlying graph would require some refactoring. We can discuss these changes as your suggestion makes a lot of sense and could be expanded in some cases.
2. That is easy enough to do, I'll address that ASAP.

Regarding outside contributions, I'll need to get back to you on that, since the crate is part of my thesis project I need to check with my advisor.

**Comment by jmg-duarte** [comment]
The latest version `0.7.1` addresses the destination issue

**Comment by jmg-duarte** [comment]
@Michael-J-Ward I've checked and outside contributions are being accepted!

**Comment by jmg-duarte** [comment]
Version `0.8.0-rc1` supports labeling enumeration variants!
Example:
![image](https://user-images.githubusercontent.com/15343819/124593672-cfcffc00-de56-11eb-921a-544167260db1.png)
https://github.com/rustype/typestate-examples/blob/650e276be08b9ad3343a6d87734daa3b48508206/auction/src/main.rs#L22-L104
